name: libfive-d CI

on: push
#   schedule:
#   - cron: '0 0 * * SUN'

jobs:
  test:
    name: Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ldc-1.33.0
    - name: Install *nix Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get install --quiet -y libboost-all-dev libeigen3-dev
    - name: Lint
      run: dub lint
    - name: Clone subprojects
      run: git submodule update --init --recursive
    - name: Cache libfive binaries
      uses: actions/cache@v3
      env:
        cache-name: cache-libfive-binaries
      with:
        path: subprojects/libfive/build
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/subprojects/libfive/CMakeLists.txt') }}
    - name: Test
      run: make libfive && dub test --coverage
    # - name: Integration Test
    #   run: make headless
    - name: Upload Coverage to Codecov
      if: success()
      run: bash <(curl -s https://codecov.io/bash)
    # - name: Upload Test Log Artifact on Failure
    #   uses: actions/upload-artifact@v1
    #   if: failure()
    #   with:
    #     name: Linux_Meson_Testlog
    #     path: build/meson-logs/testlog.txt
